#!/usr/bin/env python3
"""Generate src/TileAssets.cs — the "PAY by square" wordmark as one baked
RGB bitmap (64 px tall) plus the brand icon (64x64 RGBA).

The whole caption wordmark ("PAY" bold + "by square") is rasterised ONCE by
Pillow/dejaVu onto a white canvas and embedded as a single static byte[] in
C#.  The zero-dependency decorator therefore renders the caption by scaling
this one bitmap — no per-glyph math, no font at runtime, no System.Drawing.

Output shape (all `static readonly`, so the literals are blob-backed in the
PE and the element count can be large without hitting any method-size limit):

    public const int CapW   // wordmark width  (px)
    public const int CapH   // wordmark height (px, ~64)
    public static readonly int[] CAP_RGB   // CapW*CapH packed 0xRRGGBB, row-major, white bg
    public const int IconSize = 64
    public static readonly int[] ICON_RGBA // 64*64 packed 0xAARRGGBB
    CapPixel(x,y) -> (r,g,b)
    IconPixel(x,y) -> (r,g,b,a)

Usage:
    python3 tools/gen_caps_assets.py > src/TileAssets.cs
"""
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SIZE = 64
GAP = int(round(SIZE * 0.14))            # gap between "PAY" and "by square"
BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
REGULAR = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
PAY_TEXT = "PAY"
BY_TEXT = "by square"
PAY_COLOR = (0x4A, 0x6D, 0x9C)           # accent blue for "PAY"
BY_COLOR = (0xD8, 0xDD, 0xE2)           # light ink for "by square"
CARD = (0xFF, 0xFF, 0xFF)               # flatten the wordmark onto white
ICON = os.path.join(ROOT, "assets", "card.png")
ICON_SIZE = 64


def wordmark():
    """Render 'PAY  by square' on white at ~64 px. Returns (w, h, rgba->rgb bytes)."""
    fB = ImageFont.truetype(BOLD, SIZE)
    fR = ImageFont.truetype(REGULAR, SIZE)
    ascB, descB = fB.getmetrics()
    ascR, descR = fR.getmetrics()
    baseline = max(ascB, ascR)
    H = baseline + max(descB, descR)
    wPAY = int(round(fB.getlength(PAY_TEXT)))
    wBY = int(round(fR.getlength(BY_TEXT)))
    W = int(round(wPAY + GAP + wBY)) + 2

    canvas = Image.new("RGB", (W, H), CARD)
    d = ImageDraw.Draw(canvas)
    d.text((0, baseline - ascB), PAY_TEXT, font=fB, fill=PAY_COLOR)
    d.text((int(round(wPAY + GAP)), baseline - ascR), BY_TEXT, font=fR, fill=BY_COLOR)
    return W, H, canvas.tobytes()


def icon_rgba():
    im = Image.open(ICON).convert("RGBA").resize(
        (ICON_SIZE, ICON_SIZE), Image.Resampling.LANCZOS)
    return im.tobytes()


def emit():
    W, H, cap = wordmark()
    ib = icon_rgba()
    L = []
    L.append("// Generated by tools/gen_caps_assets.py - DO NOT EDIT BY HAND.")
    L.append("// 'PAY by square' wordmark baked as a single " + f"{W}x{H}" + " RGB bitmap")
    L.append("// (dejaVu Sans at ~64 px, white card background) and the brand")
    L.append("// icon (assets/card.png, 64x64 RGBA).  Decorator scales the")
    L.append("// wordmark bitmap into the caption row — no font / no System.")
    L.append("using System;")
    L.append("")
    L.append("namespace PayBySquare")
    L.append("{")
    L.append("    internal sealed class TileAssets")
    L.append("    {")
    L.append(f"        public const int CapW = {W};")
    L.append(f"        public const int CapH = {H};")
    L.append("")
    ind = []
    per = 16
    capN = len(cap) // 3
    for s in range(0, capN, per):
        cnt = min(per, capN - s)
        vals = ["0x%06x" % (cap[s + i * 3] << 16 | cap[s + i * 3 + 1] << 8 | cap[s + i * 3 + 2])
                for i in range(cnt)]
        ind.append("            " + ", ".join(vals))
    L.append(f"        public static readonly int[] CAP_RGB = new int[{capN}] {{")
    L.append(",\n".join(ind))
    L.append("        };")
    L.append("")
    L.append(f"        public const int IconSize = {ICON_SIZE};")
    L.append("")
    ind = []
    icN = len(ib) // 4
    for s in range(0, icN, per):
        cnt = min(per, icN - s)
        vals = []
        for i in range(cnt):
            p = ib[s + i * 4] << 24 | ib[s + i * 4 + 1] << 16 | ib[s + i * 4 + 2] << 8 | ib[s + i * 4 + 3]
            vals.append("0x%08x" % p if p < 0x80000000 else "-0x%08x" % (0x100000000 - p))
        ind.append("            " + ", ".join(vals))
    L.append(f"        public static readonly int[] ICON_RGBA = new int[{ICON_SIZE * ICON_SIZE}] {{")
    L.append(",\n".join(ind))
    L.append("        };")
    L.append("")
    L.append("        public static (int r, int g, int b) CapPixel(int x, int y)")
    L.append("        {")
    L.append("            if (x < 0 || x >= CapW || y < 0 || y >= CapH)")
    L.append("                return (255, 255, 255);")
    L.append("            int p = CAP_RGB[(y * CapW + x)] & 0xFFFFFF;")
    L.append("            return (p >> 16, p >> 8 & 255, p & 255);")
    L.append("        }")
    L.append("")
    L.append("        public static (int r, int g, int b, int a) IconPixel(int x, int y)")
    L.append("        {")
    L.append("            if (x < 0 || x >= IconSize || y < 0 || y >= IconSize) return (0, 0, 0, 0);")
    L.append("            int p = ICON_RGBA[(y * IconSize + x)];")
    L.append("            return (p >> 16 & 255, p >> 8 & 255, p & 255, p >> 24 & 255);")
    L.append("        }")
    L.append("    }")
    L.append("}")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    import sys
    sys.stdout.write(emit())
