#!/usr/bin/env python3
"""Generate src/TileAssets.cs — the "PAY by square" wordmark as one baked
RGB bitmap (64 px tall) plus the brand icon (64x64 RGBA).

The whole caption wordmark ("PAY" bold + "by square") is rasterised ONCE by
Pillow/dejaVu onto a white canvas and embedded as a single static byte[] in
C#.  The zero-dependency decorator therefore renders the caption by scaling
this one bitmap — no per-glyph math, no font at runtime, no System.Drawing.

Output shape (all `static readonly`, so the literals are blob-backed in the
PE and the element count can be large without hitting any method-size limit):

    public const int CapW   // wordmark width  (px)
    public const int CapH   // wordmark height  (px, ~64)
    public static readonly int[] CAP_RGBA  // CapW*CapH packed 0xAARRGGBB, row-major, transparent bg
    public const int IconSize = 64
    public static readonly int[] ICON_RGBA // 64*64 packed 0xAARRGGBB
    CapPixel(x,y) -> (r,g,b)
    IconPixel(x,y) -> (r,g,b,a)

Usage:
    python3 tools/gen_caps_assets.py > src/TileAssets.cs
"""
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SIZE = 64
# Gap between "PAY" and "by square" = GAPM × the natural word-space width of
# "by square" (same face/size as "by").  1.0 = "rovnako ako prirodzená medzera".
BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
REGULAR = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
PAY_TEXT = "PAY"
BY_TEXT = "by square"
import os as _os
GAPM = float(_os.environ.get("CAP_GAPM", "1.0"))
NATURAL_SPACE = ImageFont.truetype(REGULAR, SIZE).getlength(" ")
GAP = int(round(NATURAL_SPACE * GAPM))
PAY_COLOR = (0x73, 0xA6, 0xD8)           # "PAY" — same brand blue as the icon
BY_COLOR = (0xA6, 0xA7, 0xAA)           # "by square" — medium grey, clearly legible
CARD = (0xFF, 0xFF, 0xFF)               # flatten the wordmark onto white
ICON = os.path.join(ROOT, "assets", "card.png")
ICON_SIZE = 64


def wordmark():
    """Render 'PAY  by square' with true per-pixel alpha.

    Technique: draw each word (white) onto a black L-mask -> pure coverage;
    then composite a flat ink colour with that mask as alpha.  The result
    (W, H, RGBA bytes) keeps *pure* ink colours and a real alpha channel, so
    the C# side can composite correctly on ANY background.

    Returns (W, H, rgba_bytes, wPAY, wBY, GAP) — the segment widths (in the
    same 64px-tall units) so the SVG renderer can lay segments out exactly.
    """
    fB = ImageFont.truetype(BOLD, SIZE)
    fR = ImageFont.truetype(REGULAR, SIZE)
    ascB, descB = fB.getmetrics()
    ascR, descR = fR.getmetrics()
    baseline = max(ascB, ascR)
    H = baseline + max(descB, descR)
    wPAY = int(round(fB.getlength(PAY_TEXT)))
    wBY = int(round(fR.getlength(BY_TEXT)))
    W = int(round(wPAY + GAP + wBY)) + 2

    def word_mask(text, font, x, y):
        m = Image.new("L", (W, H), 0)
        ImageDraw.Draw(m).text((x, y), text, font=font, fill=255)
        return m

    transparent = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    for text, font, x, color in (
        (PAY_TEXT, fB, 0, PAY_COLOR),
        (BY_TEXT, fR, int(round(wPAY + GAP)), BY_COLOR),
    ):
        mask = word_mask(text, font, x, baseline - (ascB if font is fB else ascR))
        solid = Image.new("RGBA", (W, H), color + (255,))
        canvas = Image.composite(solid, transparent, mask)
        transparent = canvas

    return W, H, transparent.tobytes(), wPAY, wBY, GAP


def icon_rgba():
    im = Image.open(ICON).convert("RGBA").resize(
        (ICON_SIZE, ICON_SIZE), Image.Resampling.LANCZOS)
    return im.tobytes()


def emit():
    W, H, cap, wPAY, wBY, GAP = wordmark()
    ib = icon_rgba()
    # segment widths in /1024 of the wordmark width (layout for the SVG path)
    segPay = int(round(wPAY * 1024 / W))
    segGap = int(round(GAP * 1024 / W))
    L = []
    L.append("// Generated by tools/gen_caps_assets.py - DO NOT EDIT BY HAND.")
    L.append("// 'PAY by square' wordmark baked as a single " + f"{W}x{H}" + " RGB bitmap")
    L.append("// (dejaVu Sans at ~64 px, white card background) and the brand")
    L.append("// icon (assets/card.png, 64x64 RGBA).  Decorator scales the")
    L.append("// wordmark bitmap into the caption row — no font / no System.")
    L.append("using System;")
    L.append("")
    L.append("namespace PayBySquare")
    L.append("{")
    L.append("    internal sealed class TileAssets")
    L.append("    {")
    L.append(f"        public const int CapW = {W};")
    L.append(f"        public const int CapH = {H};")
    L.append(f"        // Wordmark segment widths in /1024 of CapW ('PAY' | 'by square' | gap between them)")
    L.append(f"        public const int SegPay = {segPay};")
    L.append(f"        public const int SegGap = {segGap};")
    ind = []
    per = 12
    capN = len(cap) // 4
    for sb in range(0, len(cap), per * 4):
        cnt = min(per, (len(cap) - sb) // 4)
        vals = []
        for i in range(cnt):
            r = cap[sb + i * 4]; g = cap[sb + i * 4 + 1]; b = cap[sb + i * 4 + 2]; a = cap[sb + i * 4 + 3]
            p = a << 24 | r << 16 | g << 8 | b
            vals.append("0x%08x" % p if p < 0x80000000 else "-0x%08x" % (0x100000000 - p))
        ind.append("            " + ", ".join(vals))
    L.append(f"        public static readonly int[] CAP_RGBA = new int[{capN}] {{")
    L.append(",\n".join(ind))
    L.append("        };")
    L.append("")
    L.append(f"        public const int IconSize = {ICON_SIZE};")
    L.append("")
    ind = []
    icN = len(ib) // 4
    for sb in range(0, len(ib), per * 4):
        cnt = min(per, (len(ib) - sb) // 4)
        vals = []
        for i in range(cnt):
            r = ib[sb + i * 4]; g = ib[sb + i * 4 + 1]; b = ib[sb + i * 4 + 2]; a = ib[sb + i * 4 + 3]
            p = a << 24 | r << 16 | g << 8 | b
            vals.append("0x%08x" % p if p < 0x80000000 else "-0x%08x" % (0x100000000 - p))
        ind.append("            " + ", ".join(vals))
    L.append(f"        public static readonly int[] ICON_RGBA = new int[{ICON_SIZE * ICON_SIZE}] {{")
    L.append(",\n".join(ind))
    L.append("        };")
    L.append("")
    L.append("        public static (int r, int g, int b, int a) CapPixel(int x, int y)")
    L.append("        {")
    L.append("            if (x < 0 || x >= CapW || y < 0 || y >= CapH)")
    L.append("                return (0, 0, 0, 0);")
    L.append("            int p = CAP_RGBA[(y * CapW + x)];")
    L.append("            return (p >> 16 & 255, p >> 8 & 255, p & 255, p >> 24 & 255);")
    L.append("        }")
    L.append("")
    L.append("        public static (int r, int g, int b, int a) IconPixel(int x, int y)")
    L.append("        {")
    L.append("            if (x < 0 || x >= IconSize || y < 0 || y >= IconSize) return (0, 0, 0, 0);")
    L.append("            int p = ICON_RGBA[(y * IconSize + x)];")
    L.append("            return (p >> 16 & 255, p >> 8 & 255, p & 255, p >> 24 & 255);")
    L.append("        }")
    L.append("    }")
    L.append("}")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    import sys
    sys.stdout.write(emit())
